package:
  name: llvm
  version: 3.5.0

source:
  fn: llvm-3.5.0.src.tar.xz
  url: http://llvm.org/releases/3.5.0/llvm-3.5.0.src.tar.xz
  md5: d6987305a1a0e58e128c1374cd3b8fef

build:
  number: 0

requirements:
  build:
    - system           [linux and not armv6]
    - cmake            [win]
  run:
    - system           [linux and not armv6]

test:
  commands:
    - llvm-config --version

about:
  home: http://llvm.org/
  license: Open Source (http://llvm.org/releases/3.5.0/LICENSE.TXT)
